---
name: Build and Deploy MSI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Choco package
        run: >
          Set-ExecutionPolicy Bypass -Scope Process

          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - name: install google cli
        uses: google-github-actions/setup-gcloud@vo
        with: null
        project_id: ${{secrets.GOOGLE_PROJECT}}
        service_account_key: ${{secrets.GOOGLE_APP_CRED}}
      - name: push the artifact to GCP
        env:
        keys : ${{secrets.GOOGLE_APP_CRED}}
        runs : ${{GOOGLE_PROJECT:${{secrets.GOOGLE_PROJECT}} --source=
            https://github.com/Kiranbora/msi-dep/blob/main/MSIDemo.22.0.0.43559.nupkg
            --project=${{secrets.GOOGLE_APP_CRED}} --location=$gcpRegion
            --repository=$gcpRepository --package=$packageName
            --version=$packageVersion}}
          
